/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AboutGroup: typeof import('./src/components/AboutGroup.vue')['default']
    ActionUser: typeof import('./src/components/ActionUser.vue')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Button: typeof import('./src/components/Button.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    ChatListItem: typeof import('./src/components/ChatListItem.vue')['default']
    CreatePost: typeof import('./src/components/CreatePost.vue')['default']
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    GroupSuggestItem: typeof import('./src/components/GroupSuggestItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    NotificationItem: typeof import('./src/components/NotificationItem.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostActions: typeof import('./src/components/PostActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulesGroup: typeof import('./src/components/RulesGroup.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SidebarNavItem: typeof import('./src/components/SidebarNavItem.vue')['default']
    Story: typeof import('./src/components/Story.vue')['default']
    SuggestionItem: typeof import('./src/components/SuggestionItem.vue')['default']
  }
}
